package scalaapplication1.ch06

/**
 * A Rational number (numerator, denomintor).  Constructor is automatically generated by compiler
 */
class Rational(n: Int, d: Int) {
  
  require (d != 0)
  
  val numer = n
  val denom = d
  
  def this(n: Int) = this(n, 1)  // auxillary constructor
  
  def add(that: Rational) : Rational = {
    new Rational(
      (this.numer * that.denom + that.numer * this.denom),
      (this.denom * that.denom)
    )
  }
  
  override def toString = numer + "/" + denom

}